### ISSUE TITLE
 SerializationHelper.DecimalToBinary does not work correctly

### ISSUE THREAD

**Issue by filipniziol** [GetScatter/eos-sharp#7] opened 2018-09-04 10:35 UTC
SerializationHelper.DecimalToBinary does not convert correctly to byte array
```
uint64 10001 converted to 17 
uint64 10002 converted to 18 
```

**Comment by mmcs85** [comment] 2018-09-04 14:13
I don't fallow your logic on what are you trying to convert and whats wrong.

SerializationHelper.DecimalToBinary is the same implementation from eosjs2 and converts a string to a byte[] representation in a given size.

Can you give more details on what you are trying to test? Function call?

string doubleStr = "10001";
var doubleBytes = SerializationHelper.DecimalToBinary(8, doubleStr);
returns: 17 39 0 0 0 0 0 0

var doubleBytes2 = BitConverter.GetBytes(Convert.ToUInt64(doubleStr));
returns: 17 39 0 0 0 0 0 0

same for the 16 bytes version...

Even thought I find your pull request a more cleaner solution is not as generic as the eosjs2 version. Not that we need anything othern than 4, 8, 16 bytes storage size.

**Comment by filipniziol** [comment] 2018-09-04 14:33
Strange - I wonder then why my result is
```
string doubleStr = "10001";
var doubleBytes = SerializationHelper.DecimalToBinary(8, doubleStr);
returns: 17 0 0 0 0 0 0 0
```

**Comment by mmcs85** [comment] 2018-09-04 14:39
Can you execute this on your target machine?
bool le = BitConverter.IsLittleEndian;

What is the result?

**Comment by filipniziol** [comment] 2018-09-04 15:59
The result is true.

Windows 10 Professional, 64 bit

**Comment by mmcs85** [comment] 2018-09-04 17:17
I'm using same OS and the same littleendianess this may be hardware related or you are using other version of the netstandard. Other than that I can't reproduce this behavior.

Created some unit tests for this you may try the different approaches.

Going to close this issue but feel free to repopen if you got more detail.

**Closed by mmcs85** 2018-09-04 17:17 UTC
